defmodule ExMCP.ACPShimGenerator do
  @moduledoc """
  Generates the deprecated `ExMCP.ACP.*` forwarding modules from a compiled
  `ex_acp`.

  During 1.x, `ex_acp` holds the only ACP implementation and ExMCP keeps its
  old `ExMCP.ACP.*` names alive by forwarding to it. Each public `ExACP.*`
  module gets an `ExMCP.ACP.*` counterpart that:

    * delegates every exported function (including behaviour and GenServer
      callbacks, so the shim can be passed anywhere a module name is expected,
      e.g. `adapter: ExMCP.ACP.Adapters.Codex`, and `function_exported?/3`
      answers the same as for the real module),
    * aliases every public type (`@type t :: ExACP.X.t()`),
    * re-declares behaviour callbacks so `@behaviour ExMCP.ACP.Agent.Handler`
      keeps compiling without warnings,
    * marks the module and each function deprecated, pointing at `ExACP`.

  Structs are not forwarded. A struct is bound to its module name, so values
  are `%ExACP.X{}` and `%ExMCP.ACP.X{}` patterns stop matching. None of the
  ACP structs are documented data types (they are GenServer, adapter, or
  transport state), which is why this is acceptable in a minor release.

  Only modules that existed as `ExMCP.ACP.*` at the split get shims, from two
  lists frozen then. `@public_modules` get documented shims.
  `@hidden_modules` (helpers that were never meant to be public) get
  `@moduledoc false` shims that keep 1.x callers working without advertising
  them. Modules added to ex_acp later have no legacy name to preserve. If a
  listed module disappears from ex_acp, or a public one becomes
  `@moduledoc false`, the generator raises so the break is a deliberate
  decision. Macros are
  not supported; the generator raises if a public module exports one so a
  hand-written shim can be considered.

  It also emits `ExMCP.ACP.TelemetryCompat`, which re-emits every event in
  `ExACP.Telemetry.events/0` under its pre-split name (`[:ex_mcp, :acp | _]`,
  or `[:ex_mcp, :transport | _]` for the stdio transport's events), so
  existing telemetry handlers keep firing. The ExMCP application attaches it
  at boot (one line in `start/2`, added at cutover).
  """

  @target_root ExMCP.ACP

  # The ExMCP.ACP modules that existed at the split, under their ex_acp names.
  # Do not add modules introduced in ex_acp after the split: they have no
  # legacy name to preserve.
  #
  # Public: documented API. Shims are documented, deprecated forwarders.
  @public_modules [
    ExACP,
    ExACP.Adapter,
    ExACP.AdapterBridge,
    ExACP.AdapterEvents,
    ExACP.Adapters.ClaudeSDK,
    ExACP.Adapters.ClaudeSDK.SessionStore,
    ExACP.Adapters.Codex,
    ExACP.Adapters.Pi,
    ExACP.Adapters.ZCode,
    ExACP.AdapterTransport,
    ExACP.Agent,
    ExACP.Agent.Handler,
    ExACP.Agent.Transport,
    ExACP.Agent.Transport.Memory,
    ExACP.Agent.Transport.Stdio,
    ExACP.Capabilities,
    ExACP.Client,
    ExACP.Client.DefaultHandler,
    ExACP.Client.Handler,
    ExACP.Protocol,
    ExACP.Registry,
    ExACP.Types
  ]

  # Hidden: modules that had a moduledoc in 1.x but were never intended as
  # public API, and were made `@moduledoc false` before the split (see the
  # CHANGELOG). Shims are `@moduledoc false` forwarders so 1.x callers keep
  # working until 2.0 removes every ExMCP.ACP module.
  @hidden_modules [
    ExACP.Adapters.ClaudeSDK.Mapper,
    ExACP.Adapters.ClaudeSDK.Protocol,
    ExACP.Adapters.ClaudeSDK.ToolInfo,
    ExACP.Adapters.Codex.Config,
    ExACP.Adapters.Codex.Events,
    ExACP.Adapters.Codex.FileChanges,
    ExACP.Adapters.Codex.Protocol,
    ExACP.Adapters.Codex.Sessions,
    ExACP.Adapters.Codex.SlashCommands,
    ExACP.Adapters.Pi.RPC,
    ExACP.Adapters.ZCode.Config,
    ExACP.Adapters.ZCode.Mapper,
    ExACP.Adapters.ZCode.Protocol,
    ExACP.Adapters.ZCode.Sessions,
    ExACP.Envelope,
    ExACP.LifecycleParams,
    ExACP.Maps,
    ExACP.Meta,
    ExACP.NameValue,
    ExACP.PromptQueue
  ]

  @skip_functions [__info__: 1, module_info: 0, module_info: 1, behaviour_info: 1] ++
                    [__struct__: 0, __struct__: 1]

  @header "# Generated by `mix acp.gen_shims`. Do not edit; rerun the task instead.\n"

  @doc """
  Returns `%{relative_path => source}` for every shim, rooted at `lib/ex_mcp/`.
  """
  @spec generate() :: %{String.t() => String.t()}
  def generate do
    Application.load(:ex_acp)

    available =
      case Application.spec(:ex_acp, :modules) do
        nil -> Mix.raise("ex_acp is not available; add it as a dependency first")
        modules -> modules
      end

    case (@public_modules ++ @hidden_modules) -- available do
      [] ->
        :ok

      missing ->
        Mix.raise(
          "ex_acp no longer provides #{inspect(missing)}; removing an ExMCP.ACP " <>
            "module is a breaking change, so handle it deliberately"
        )
    end

    Enum.each(@public_modules, &ensure_documented!/1)
    Enum.each(@hidden_modules, &Code.ensure_loaded!/1)

    vsn = to_string(Application.spec(:ex_acp, :vsn))

    Enum.map(@public_modules, &{&1, :public})
    |> Enum.concat(Enum.map(@hidden_modules, &{&1, :hidden}))
    |> Map.new(fn {mod, visibility} -> {path_for(mod), render(mod, visibility, vsn)} end)
    |> Map.put("acp/telemetry_compat.ex", format(@header <> telemetry_compat()))
  end

  @doc "Maps `ExACP.Foo.Bar` to `ExMCP.ACP.Foo.Bar`."
  def target_module(mod) do
    case Module.split(mod) do
      ["ExACP" | rest] -> Module.concat([@target_root | rest])
    end
  end

  defp path_for(mod) do
    case Module.split(mod) do
      ["ExACP"] -> "acp.ex"
      ["ExACP" | rest] -> Path.join(["acp" | Enum.map(rest, &Macro.underscore/1)]) <> ".ex"
    end
  end

  defp ensure_documented!(mod) do
    Code.ensure_loaded!(mod)

    case Code.fetch_docs(mod) do
      {:docs_v1, _, _, _, :hidden, _, _} ->
        Mix.raise("#{inspect(mod)} is now @moduledoc false, but ExMCP.ACP exposed it in 1.x")

      {:docs_v1, _, _, _, _, _, _} ->
        :ok

      {:error, reason} ->
        Mix.raise("No docs chunk for #{inspect(mod)}: #{inspect(reason)}")
    end
  end

  ## Rendering

  defp render(mod, visibility, vsn) do
    if mod.__info__(:macros) != [] do
      Mix.raise(
        "#{inspect(mod)} exports macros #{inspect(mod.__info__(:macros))}; " <>
          "macros cannot be forwarded with defdelegate and need a hand-written shim"
      )
    end

    target = target_module(mod)
    docs = function_docs(mod)

    body =
      [
        moduledoc(mod, visibility, vsn),
        types(mod),
        callbacks(mod),
        functions(mod, visibility, docs)
      ]
      |> Enum.reject(&(&1 == ""))
      |> Enum.join("\n")

    format(@header <> "defmodule #{inspect(target)} do\n" <> body <> "end\n")
  end

  defp format(source) do
    source |> Code.format_string!() |> IO.iodata_to_binary() |> Kernel.<>("\n")
  end

  defp telemetry_compat do
    ~S'''
    defmodule ExMCP.ACP.TelemetryCompat do
      @moduledoc false

      # Re-emits ex_acp telemetry under the names ExMCP used before ACP moved
      # to its own package, so handlers attached to `[:ex_mcp, :acp, ...]`
      # (and to `[:ex_mcp, :transport, ...]` for ACP stdio connections) keep
      # firing during 1.x. Attached by ExMCP.Application; removed in 2.0.

      @handler_id "ex_mcp-acp-telemetry-compat"

      @spec attach() :: :ok
      def attach do
        case :telemetry.attach_many(
               @handler_id,
               ExACP.Telemetry.events(),
               &__MODULE__.handle_event/4,
               nil
             ) do
          :ok -> :ok
          {:error, :already_exists} -> :ok
        end
      end

      @spec detach() :: :ok | {:error, :not_found}
      def detach, do: :telemetry.detach(@handler_id)

      @doc false
      def handle_event(event, measurements, metadata, _config) do
        :telemetry.execute(legacy_event(event), measurements, metadata)
      end

      @doc false
      @spec legacy_event([atom(), ...]) :: [atom(), ...]
      def legacy_event([:ex_acp, :transport, kind | rest]) when kind in [:connection, :message],
        do: [:ex_mcp, :transport, kind | rest]

      def legacy_event([:ex_acp | rest]), do: [:ex_mcp, :acp | rest]
    end
    '''
  end

  defp moduledoc(mod, :hidden, vsn) do
    """
      @moduledoc false

      # Internal ACP helper: forwards to #{inspect(mod)} (ex_acp #{vsn}).
      # Never public API; kept only so 1.x callers do not break. Removed in
      # ExMCP 2.0 with the rest of ExMCP.ACP.
    """
  end

  defp moduledoc(mod, :public, vsn) do
    struct_note =
      if function_exported?(mod, :__struct__, 0) do
        """

        `%#{inspect(target_module(mod))}{}` no longer exists: this module's
        struct is `%#{inspect(mod)}{}`, so match on that instead.
        """
      else
        ""
      end

    """
      @moduledoc \"\"\"
      Deprecated alias for `#{inspect(mod)}`.

      Every function forwards to `#{inspect(mod)}` (ex_acp #{vsn}). This module
      will be removed in ExMCP 2.0; depend on `:ex_acp` and call
      `#{inspect(mod)}` directly.#{String.trim_trailing(struct_note)}
      \"\"\"
      @moduledoc deprecated: "Use #{inspect(mod)} from the ex_acp package"
    """
  end

  ## Types

  defp types(mod) do
    {:ok, types} = Code.Typespec.fetch_types(mod)
    callbacks = fetch_callbacks(mod)

    public =
      for {kind, {name, _, args}} <- types, kind in [:type, :opaque] do
        vars = Enum.map(args, &type_var_name/1)
        head = type_call(name, vars)
        remote = "#{inspect(mod)}.#{type_call(name, vars)}"
        "  @type #{head} :: #{remote}\n"
      end

    # Callback specs may reference private types, which cannot be referenced
    # remotely, so copy the definitions of the ones actually reachable.
    private_defs =
      for {:typep, {name, _, args} = type} <- types, into: %{}, do: {{name, length(args)}, type}

    needed = reachable_private_types(callbacks, private_defs)

    private =
      for {key, type} <- private_defs, key in needed do
        "  @typep " <> Macro.to_string(Code.Typespec.type_to_quoted(type)) <> "\n"
      end

    Enum.join(public ++ private)
  end

  defp type_var_name({:var, _, name}), do: Atom.to_string(name)
  defp type_var_name(_), do: "_"

  defp type_call(name, vars), do: "#{name}(#{Enum.join(vars, ", ")})"

  defp reachable_private_types(callbacks, private_defs) do
    roots =
      Enum.flat_map(callbacks, fn {{name, _arity}, specs} ->
        Enum.map(specs, &Code.Typespec.spec_to_quoted(name, &1))
      end)

    walk(roots, private_defs, MapSet.new())
  end

  defp walk([], _defs, seen), do: seen

  defp walk([ast | rest], defs, seen) do
    {_, found} =
      Macro.prewalk(ast, [], fn
        {name, _, args} = node, acc when is_atom(name) and is_list(args) ->
          key = {name, length(args)}
          if Map.has_key?(defs, key), do: {node, [key | acc]}, else: {node, acc}

        node, acc ->
          {node, acc}
      end)

    new = Enum.reject(found, &MapSet.member?(seen, &1))
    seen = Enum.into(new, seen)
    more = Enum.map(new, &Code.Typespec.type_to_quoted(Map.fetch!(defs, &1)))
    walk(more ++ rest, defs, seen)
  end

  ## Callbacks

  defp fetch_callbacks(mod) do
    case Code.Typespec.fetch_callbacks(mod) do
      {:ok, callbacks} -> Enum.sort(callbacks)
      :error -> []
    end
  end

  defp callbacks(mod) do
    case fetch_callbacks(mod) do
      [] ->
        ""

      callbacks ->
        specs =
          for {{name, arity}, specs} <- callbacks, spec <- specs do
            quoted = Code.Typespec.spec_to_quoted(name, spec)

            "  @doc \"See `c:#{inspect(mod)}.#{name}/#{arity}`.\"\n" <>
              "  @callback " <> Macro.to_string(quoted) <> "\n"
          end

        optional =
          case mod.behaviour_info(:optional_callbacks) do
            [] -> ""
            list -> "  @optional_callbacks #{inspect(Enum.sort(list))}\n"
          end

        Enum.join(specs) <> optional
    end
  end

  ## Functions

  defp function_docs(mod) do
    {:docs_v1, _, _, _, _, _, entries} = Code.fetch_docs(mod)

    for {{:function, name, arity}, _anno, signatures, doc, meta} <- entries, into: %{} do
      defaults = Map.get(meta, :defaults, 0)
      {{name, arity}, %{signatures: signatures, hidden?: doc == :hidden, defaults: defaults}}
    end
  end

  defp functions(mod, visibility, docs) do
    exports =
      (mod.__info__(:functions) -- @skip_functions)
      |> Enum.sort()

    Enum.map_join(exports, "\n", fn {name, arity} ->
      {entry, signature} = doc_entry(docs, name, arity)
      args = arg_names(signature, arity)
      replacement = "#{inspect(mod)}.#{name}/#{arity}"

      doc =
        if visibility == :hidden or entry.hidden?,
          do: "  @doc false\n",
          else: "  @doc \"See `#{replacement}`.\"\n"

      deprecation =
        if visibility == :hidden,
          do: "Internal ACP helper; removed in ExMCP 2.0",
          else: "Use #{replacement} instead"

      doc <>
        "  @deprecated \"#{deprecation}\"\n" <>
        "  defdelegate #{fun_head(name, args)}, to: #{inspect(mod)}\n"
    end)
  end

  # A function with default arguments is documented once, under its highest
  # arity; the lower arities borrow that entry and its signature.
  defp doc_entry(docs, name, arity) do
    case Map.fetch(docs, {name, arity}) do
      {:ok, entry} ->
        {entry, List.first(entry.signatures)}

      :error ->
        docs
        |> Enum.filter(fn {{n, a}, e} -> n == name and a > arity and a - e.defaults <= arity end)
        |> Enum.min_by(fn {{_, a}, _} -> a end, fn -> nil end)
        |> case do
          {_key, entry} -> {entry, List.first(entry.signatures)}
          nil -> {%{hidden?: true}, nil}
        end
    end
  end

  defp fun_head(name, args) do
    call = Macro.to_string({name, [], Enum.map(args, &{&1, [], nil})})

    # Plain identifiers (including `connected?`-style names) render as a
    # normal call; anything that would need quoting is refused.
    if Macro.classify_atom(name) == :identifier,
      do: call,
      else: Mix.raise("Cannot delegate #{inspect(name)}: unsupported function name")
  end

  # Reuse the argument names from the documented signature when they are
  # plain, unique variables; otherwise fall back to arg1..argN. For a lower
  # arity of a function with defaults, Elixir drops the rightmost defaulted
  # parameters first, so the same is done here.
  defp arg_names(signature, arity) do
    fallback = for i <- 1..arity//1, do: :"arg#{i}"

    with sig when is_binary(sig) <- signature,
         {:ok, {_fun, _, params}} when is_list(params) <- Code.string_to_quoted(sig),
         names when length(names) == arity <- drop_defaults(params, length(params) - arity),
         names = Enum.map(names, &plain_arg/1),
         true <- Enum.all?(names, &is_atom/1) and Enum.uniq(names) == names do
      names
    else
      _ -> fallback
    end
  end

  defp drop_defaults(params, 0), do: params

  defp drop_defaults(params, count) do
    {kept, _} =
      params
      |> Enum.reverse()
      |> Enum.reduce({[], count}, fn
        {:\\, _, _}, {acc, n} when n > 0 -> {acc, n - 1}
        param, {acc, n} -> {[param | acc], n}
      end)

    kept
  end

  defp plain_arg({:\\, _, [arg, _default]}), do: plain_arg(arg)

  defp plain_arg({name, _, ctx}) when is_atom(name) and is_atom(ctx) do
    str = Atom.to_string(name)
    if String.starts_with?(str, "_"), do: nil, else: name
  end

  defp plain_arg(_), do: nil
end
