name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  MIX_ENV: test

jobs:
  test:
    name: Test on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['27.0']
        elixir: ['1.17.3']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Check formatting
      run: mix format --check-formatted
    
    - name: Run credo
      run: mix credo --strict
    
    - name: Check for skipped tests
      run: ./scripts/check_skip_tags.sh all
    
    - name: Check for unused dependencies
      run: mix deps.unlock --check-unused
    
    - name: Compile without warnings
      run: mix compile --warnings-as-errors
    
    - name: Run unit and integration tests
      run: mix test --exclude compliance
    
    - name: Run security check
      run: mix sobelow --skip

  # New compliance test jobs for each MCP version
  compliance-2024-11-05:
    name: MCP 2024-11-05 Compliance
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27.0'
        elixir-version: '1.17.3'
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Compile
      run: mix compile
    
    - name: Run MCP 2024-11-05 compliance tests
      run: mix test.suite compliance
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compliance-2025-03-26:
    name: MCP 2025-03-26 Compliance
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27.0'
        elixir-version: '1.17.3'
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Compile
      run: mix compile
    
    - name: Run MCP 2025-03-26 compliance tests
      run: mix test.suite compliance
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compliance-2025-06-18:
    name: MCP 2025-06-18 Compliance
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27.0'
        elixir-version: '1.17.3'
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Compile
      run: mix compile
    
    - name: Run MCP 2025-06-18 compliance tests
      run: mix test.suite compliance
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Combined compliance test job for coverage
  compliance-coverage:
    name: Compliance Test Coverage
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27.0'
        elixir-version: '1.17.3'
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Compile
      run: mix compile
    
    - name: Run all compliance tests with coverage
      run: mix coveralls.github --only compliance
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27.0'
        elixir-version: '1.17.3'
    
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    
    - name: Restore PLT cache
      uses: actions/cache@v4
      id: plt_cache
      with:
        path: priv/plts
        key: ${{ runner.os }}-plt-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-plt-
    
    - name: Install dependencies
      run: mix deps.get
    
    - name: Create PLTs
      if: steps.plt_cache.outputs.cache-hit != 'true'
      run: mix dialyzer --plt
    
    - name: Run dialyzer
      run: mix dialyzer --format github
